### ISSUE TITLE
ERROR: File to import not found or unreadable: @material/rtl/mixins

### ISSUE THREAD

**Issue by wzup** [material-components/material-components-web#1048]
Why does it happen? I do everything by you tutorial, why error?

You say [here](https://github.com/material-components/material-components-web/tree/master/packages/mdc-form-field#rtl-support)
> `mdc-form-field` is automatically RTL-aware

Since the error is thrown, it's not true, isn't it? How to solve it?

**UPD**:

![node_modules_ material_rtl 2017-07-31 13 04 34](https://user-images.githubusercontent.com/3880497/28763487-1924914a-75f1-11e7-964e-c0ebc75ab42b.png)

```
ERROR in ./src/sass/globals.scss
    Module build failed: ModuleBuildError: Module build failed:
    undefined
    ^
          File to import not found or unreadable: @material/rtl/mixins
    Parent style sheet: C:/Users/user/app/node_modules/@material/form-field/mdc-form-field.scss
          in C:\Users\user\app\node_modules\@material\form-field\mdc-form-field.scss (line 17, column 1)
        at runLoaders (C:\Users\user\app\node_modules\webpack\lib\NormalModule.js:194:19)
        at C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:364:11
        at C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:230:18
        at context.callback (C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at Object.asyncSassJobQueue.push [as callback] (C:\Users\user\app\node_modules\sass-loader\lib\loader.js:55:13)
        at Object.<anonymous> (C:\Users\user\app\node_modules\async\dist\async.js:2244:31)
        at Object.callback (C:\Users\user\app\node_modules\async\dist\async.js:906:16)
        at options.error (C:\Users\user\app\node_modules\node-sass\lib\index.js:289:32)
     @ ./src/js/App.js 17:14-37
     @ ./src/js/routes.js
     @ ./src/js/browser.js

    ERROR in ./src/sass/globals.scss
    Module build failed: ModuleBuildError: Module build failed:
    undefined
    ^
          File to import not found or unreadable: @material/rtl/mixins
    Parent style sheet: C:/Users/user/app/node_modules/@material/form-field/mdc-form-field.scss
          in C:\Users\user\app\node_modules\@material\form-field\mdc-form-field.scss (line 17, column 1)
        at runLoaders (C:\Users\user\app\node_modules\webpack\lib\NormalModule.js:194:19)
        at C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:364:11
        at C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:230:18
        at context.callback (C:\Users\user\app\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
        at Object.asyncSassJobQueue.push [as callback] (C:\Users\user\app\node_modules\sass-loader\lib\loader.js:55:13)
        at Object.<anonymous> (C:\Users\user\app\node_modules\async\dist\async.js:2244:31)
        at Object.callback (C:\Users\user\app\node_modules\async\dist\async.js:906:16)
        at options.error (C:\Users\user\app\node_modules\node-sass\lib\index.js:289:32)
```

**Comment by yeelan0319** [comment]
Hi @wzup 
Could you make sure if `node_modules` included in your webpack config path. Could you help us confirm if #692 could solve the problem of your case?

**Comment by abhiomkar** [comment]
Closing since inactive.
