### ISSUE TITLE
Aurelia framework example throws error and fails to start

### ISSUE THREAD

**Issue by krishnaxv** [material-components/material-components-web#120]
Aurelia framework example throws error with `npm start` on CLI and fails to start.

```
/home/krishnaxv/Desktop/material-components-web/framework-examples/aurelia/node_modules/webpack-dev-server/lib/Server.js:23
	var validationErrors = webpack.validateSchema(optionsSchema, options);
                                ^
TypeError: webpack.validateSchema is not a function
    at new Server (/home/krishnaxv/Desktop/material-components-web/framework-examples/aurelia/node_modules/webpack-dev-server/lib/Server.js:23:33)
    at startDevServer (/home/krishnaxv/Desktop/material-components-web/framework-examples/aurelia/node_modules/webpack-dev-server/bin/webpack-dev-server.js:378:12)
    at processOptions (/home/krishnaxv/Desktop/material-components-web/framework-examples/aurelia/node_modules/webpack-dev-server/bin/webpack-dev-server.js:316:3)
    at Object.<anonymous> (/home/krishnaxv/Desktop/material-components-web/framework-examples/aurelia/node_modules/webpack-dev-server/bin/webpack-dev-server.js:440:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
```

**OS:** Ubuntu 14.04 LTS

**Steps to reproduce bug:**
1. Run `npm start` in material-components-web/framework-examples/aurelia/ directory
2. Check CLI

**Comment by traviskaufman** [comment]
Thanks for reporting all of these :)
