### ISSUE TITLE
Getting started guide is broken because of babel

### ISSUE THREAD

**Issue by CyborgSemon** [material-components/material-components-web#3664]
The getting started guide breaks when you get to step 3 (installing babel). I think babel has updated and the npm command to install all the babel stuff in the get started guide doesn't seem to get the right stuff? Im assuming thats why it breaks.

Anyway, this is the error I get in terminal when I run `npm start`

ERROR in ./app.js
Module build failed: Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/simon/Desktop/testing3/node_modules/babel-loader/lib/index.js:8:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.scss ./app.js

ERROR in (webpack)-dev-server/client?http://localhost:8080
Module build failed: Error: Cannot find module '@babel/core'
 babel-loader@8 requires Babel 7.x (the package '@babel/core'). If you'd like to use Babel 6.x ('babel-core'), you should install 'babel-loader@7'.
    at Function.Module._resolveFilename (module.js:548:15)
    at Function.Module._load (module.js:475:25)
    at Module.require (module.js:597:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/simon/Desktop/testing3/node_modules/babel-loader/lib/index.js:8:11)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./app.scss ./app.js
webpack: Failed to compile.

Im quite confused as I'm completely new to MDC and npm and not quite sure if the getting started guide is broken or if I have done something wrong.

**Comment by kfranqueiro** [comment]
Interesting... it appears that babel-loader now points `latest` to 8.x which requires `babel-core` 7, but `babel-core` still points `latest` to 6.x. We should probably pin both within the getting-started guide to be safe.

**Comment by CyborgSemon** [comment]
@kfranqueiro It now breaks when I try the new npm command 
`npm install --save-dev babel-core@7 babel-loader@6 babel-preset-es2015 babel-plugin-transform-object-assign`
This is the error in terminal:

npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update! 
npm ERR! code ETARGET
npm ERR! notarget No matching version found for babel-core@7
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/simon/.npm/_logs/2018-09-28T01_24_09_457Z-debug.log

**Comment by kfranqueiro** [comment]
Oh jeez, I transposed the two numbers when I updated the guide. It should be babel-core@6 and babel-loader@7. I'll send another PR.
