### ISSUE TITLE
[material/drawer] Error on webpack 

### ISSUE THREAD

**Issue by ArthurJam** [material-components/material-components-web#5662]
## Bug report
Cant "compile" after installation of material/drawer

### Steps to reproduce
1. yarn add @material/drawer
2. yarn run webpack --mode development
3. get an error

### Error
```
ERROR in ./assets/styles/index.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: (varname: --mdc-typography-font-family, fallback: Roboto, sans-serif) isn't a valid CSS value.
   ╷
86 │   @return var(#{$var}, $fallback);
   │                        ^^^^^^^^^
   ╵
  node_modules/@material/theme/_functions.scss 86:24            var-()
  node_modules/@material/theme/_mixins.scss 75:19               prop()
  node_modules/@material/typography/_mixins.scss 78:9           @content
  node_modules/@material/feature-targeting/_mixins.scss 41:5    targets()
  node_modules/@material/typography/_mixins.scss 64:3           typography()
  node_modules/@material/top-app-bar/mdc-top-app-bar.scss 71:5  @use
  /var/www/assets/styles/index.scss 1:1                                                     root stylesheet
    at /var/www/node_modules/webpack/lib/NormalModule.js:316:20
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /var/www/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/var/www/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /var/www/node_modules/sass-loader/dist/index.js:73:7
    at Function.call$2 (/var/www/node_modules/sass/sass.dart.js:87178:16)
    at _render_closure1.call$2 (/var/www/node_modules/sass/sass.dart.js:76969:12)
    at _RootZone.runBinary$3$3 (/var/www/node_modules/sass/sass.dart.js:25517:18)
    at _RootZone.runBinary$3 (/var/www/node_modules/sass/sass.dart.js:25521:19)
    at _FutureListener.handleError$1 (/var/www/node_modules/sass/sass.dart.js:23971:19)
    at _Future__propagateToListeners_handleError.call$0 (/var/www/node_modules/sass/sass.dart.js:24267:40)
    at Object._Future__propagateToListeners (/var/www/node_modules/sass/sass.dart.js:3500:88)
    at _Future._completeError$2 (/var/www/node_modules/sass/sass.dart.js:24095:9)
    at _AsyncAwaitCompleter.completeError$2 (/var/www/node_modules/sass/sass.dart.js:23487:12)
    at Object._asyncRethrow (/var/www/node_modules/sass/sass.dart.js:3256:17)
    at /var/www/node_modules/sass/sass.dart.js:13327:20
    at _wrapJsFunctionForAsync_closure.$protected (/var/www/node_modules/sass/sass.dart.js:3279:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/var/www/node_modules/sass/sass.dart.js:23508:12)
    at _awaitOnObject_closure0.call$2 (/var/www/node_modules/sass/sass.dart.js:23500:25)
    at _RootZone.runBinary$3$3 (/var/www/node_modules/sass/sass.dart.js:25517:18)
    at _RootZone.runBinary$3 (/var/www/node_modules/sass/sass.dart.js:25521:19)
    at _FutureListener.handleError$1 (/var/www/node_modules/sass/sass.dart.js:23971:19)
    at _Future__propagateToListeners_handleError.call$0 (/var/www/node_modules/sass/sass.dart.js:24267:40)
    at Object._Future__propagateToListeners (/var/www/node_modules/sass/sass.dart.js:3500:88)
    at _Future._completeError$2 (/var/www/node_modules/sass/sass.dart.js:24095:9)
    at _AsyncAwaitCompleter.completeError$2 (/var/www/node_modules/sass/sass.dart.js:23487:12)
    at Object._asyncRethrow (/var/www/node_modules/sass/sass.dart.js:3256:17)
    at /var/www/node_modules/sass/sass.dart.js:15982:20
    at _wrapJsFunctionForAsync_closure.$protected (/var/www/node_modules/sass/sass.dart.js:3279:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/var/www/node_modules/sass/sass.dart.js:23508:12)
 @ ./assets/js/index.js 1:0-30
```

### Your Environment:

| Software         | Version(s) |
| ---------------- | ---------- |
| MDC Web        | 5.1.0
| Webpack          | 4.41.6
| Operating System | Docker alpine image |

    "@material/button": "^5.1.0",
    "@material/data-table": "^5.0.0",
    "@material/drawer": "^5.1.0",
    "@material/icon-button": "^5.0.0",
    "@material/top-app-bar": "^5.0.0"

### Configuration of webpack for sass

```
{
    loader: 'sass-loader',
    options: {
          implementation: require('sass'),
          sassOptions: {
              includePaths: ['node_modules'],
         }
    },
 }
```

### Additional context

Before installation of this module, the command works.

**Comment by asyncLiz** [comment]
Make sure all of your `@material/*` packages are aligned to the same version number. v5.1.0 is needed for typography, otherwise you'll get this error.
