### ISSUE TITLE
SassError: There is no module with the namespace "select"

### ISSUE THREAD

**Issue by maicol07** [material-components/material-components-web#6011]
Little question about Sass namespaces.
I've imported mdc-select with
```
@use "~@material/select/mdc-select";
@use "~@material/select/mixins";
```
in order to do this:
```
.mdc-select--compact {
    @include select.density(-4);
}
```
but it doesn't find the namespace...
What I'm doing wrong?
Thanks

Full stack trace:
```
ERROR in ./resources/sass/auth.scss
Module build failed (from ./node_modules/css-loader/index.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: There is no module with the namespace "select".
    ╷
130 │     @include select.density(-4);
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
  resources\sass\_material.scss 130:5  @import
  D:\Maicol\Documents\Progetti\Web\account\resources\sass\auth.scss 8:9                            root stylesheet
    at D:\Maicol\Documents\Progetti\Web\account\node_modules\webpack\lib\NormalModule.js:316:20
    at D:\Maicol\Documents\Progetti\Web\account\node_modules\loader-runner\lib\LoaderRunner.js:367:11
    at D:\Maicol\Documents\Progetti\Web\account\node_modules\loader-runner\lib\LoaderRunner.js:233:18
    at context.callback (D:\Maicol\Documents\Progetti\Web\account\node_modules\loader-runner\lib\LoaderRunner.js:111:13)
    at D:\Maicol\Documents\Progetti\Web\account\node_modules\sass-loader\dist\index.js:73:7
    at Function.call$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:88455:16)
    at _render_closure1.call$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:77847:12)
    at _RootZone.runBinary$3$3 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:26320:18)
    at _RootZone.runBinary$3 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:26324:19)
    at _FutureListener.handleError$1 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24768:19)
    at _Future__propagateToListeners_handleError.call$0 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:25065:40)
    at Object._Future__propagateToListeners (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:4311:88)
    at _Future._completeError$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24893:9)
    at _AsyncAwaitCompleter.completeError$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24285:12)
    at Object._asyncRethrow (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:4065:17)
    at D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:14183:20
    at _wrapJsFunctionForAsync_closure.$protected (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:4090:15)
    at _wrapJsFunctionForAsync_closure.call$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24306:12)
    at _awaitOnObject_closure0.call$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24298:25)
    at _RootZone.runBinary$3$3 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:26320:18)
    at _RootZone.runBinary$3 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:26324:19)
    at _FutureListener.handleError$1 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24768:19)
    at _Future__propagateToListeners_handleError.call$0 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:25065:40)
    at Object._Future__propagateToListeners (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:4311:88)
    at _Future._completeError$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24893:9)
    at _AsyncAwaitCompleter.completeError$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24285:12)
    at Object._asyncRethrow (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:4065:17)
    at D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:16818:20
    at _wrapJsFunctionForAsync_closure.$protected (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:4090:15)
    at _wrapJsFunctionForAsync_closure.call$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24306:12)
    at _awaitOnObject_closure0.call$2 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24298:25)
    at _RootZone.runBinary$3$3 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:26320:18)
    at _RootZone.runBinary$3 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:26324:19)
    at _FutureListener.handleError$1 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:24768:19)
    at _Future__propagateToListeners_handleError.call$0 (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:25065:40)
    at Object._Future__propagateToListeners (D:\Maicol\Documents\Progetti\Web\account\node_modules\sass\sass.dart.js:4311:88)
 @ multi ./resources/js/_material.js ./resources/js/app.js ./resources/sass/app.scss ./resources/sass/auth.scss /js/app[3]
```

**Comment by asyncLiz** [comment]
Change
```scss
@use "~@material/select/mixins";
```
to
```scss
@use "~@material/select";
```

The Sass module system uses the last file name as the _namespace_. You had two namespaces in your example: "mdc-select" and "mixins", so you got an error because there was no namespace named "select".

You can also alias the "mixins" namespace in Sass:

```scss
@use "~@material/select/mixins" as select;
```

We don't generally recommend this. Instead we recommend using the `@material/select` index bundle since it's simpler and avoids breaking changes if we move mixins around or refactor file names. 

However, if you're using `sass-loader` (looks like you are with the `~` syntax) and running into the [sass-loader index bug](https://github.com/webpack-contrib/sass-loader/issues/804), this would be an acceptable workaround if the [`webpackImporter: false`](https://github.com/webpack-contrib/sass-loader/issues/804#issuecomment-586095020) fix doesn't work for you.

**Comment by maicol07** [comment]
@asyncLiz thanks for your detailed answer.
However, I'm having the following issue with the `webpackImporter` option:
```
SassError: Can't find stylesheet to import.
  ╷
5 │ ┌ @use "~@material/theme" with (
6 │ │   $primary: $primary,
7 │ │   $secondary: $secondary,
8 │ │   $background: #fff,
9 │ │ );
  │ └─^
  ╵
```

The same error with the other `@use` statements

**Comment by maicol07** [comment]
Tried with the `as` workaround, but keep getting this error:
SassError: Undefined mixin.
    ╷
131 │     @include select.density(-4);
    │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ╵
and I don't know why... 🤷

**Comment by asyncLiz** [comment]
Two issues:

1. If you're using `webpackImporter: false`, you cannot use webpack's tilde `~` import syntax. Drop the `~` in your Sass module imports paths.
2. Select does not have a mixin named `density()` in the lastest v6.0.0 version (though there is a `filled-density()` mixin in the canary version). If you're on the latest v6, you can try setting changing the height with `@include select.height(40px);`

**Comment by maicol07** [comment]
Thank you! Fixed with the as workaround and the height mixin!
